drop view if exists ml_temp_predict_yahoo;
create view ml_temp_predict_yahoo as select * from (with a as (
	 select sql_query.*, statistical_metrics_avg.avg_volume, statistical_metrics_avg.avg_close, statistical_metrics_avg._date_count, statistical_metrics_std.std_close, statistical_metrics_std.std_volume from ((select ticker, _date, close as close, volume as volume  from yahoo_result
where
 _date in (select distinct _date from yahoo_result order by _date desc limit 55)
) sql_query join
(select ticker,  avg(volume) as avg_volume, avg(close) as avg_close, count(*) as _date_count  from yahoo_result
where _date > CURRENT_DATE - INTERVAL '40 day'
group by ticker
having avg(volume)<>0 and avg(close)<>0
) statistical_metrics_avg
on sql_query.ticker = statistical_metrics_avg.ticker join (select ticker, sqrt(sum(std_close_unsum)) as std_close, sqrt(sum(std_volume_unsum)) as std_volume from
	(select fr.ticker, fr._date, power(close - avg_close,2)/_date_count as std_close_unsum, power(volume - avg_volume,2)/_date_count as std_volume_unsum 	from yahoo_result fr join (select ticker,  avg(volume) as avg_volume, avg(close) as avg_close, count(*) as _date_count  from yahoo_result
where _date > CURRENT_DATE - INTERVAL '40 day'
group by ticker
having avg(volume)<>0 and avg(close)<>0
) avg
	 on fr.ticker = avg.ticker where fr._date > CURRENT_DATE - INTERVAL '40 day')
where _date > CURRENT_DATE - INTERVAL '40 day'
group by ticker) statistical_metrics_std
on sql_query.ticker = statistical_metrics_std.ticker) where statistical_metrics_avg.avg_volume <>0 and statistical_metrics_avg.avg_close <>0)
, b as ( select *,
 lag (volume,1) OVER (PARTITION BY ticker ORDER BY _date) AS volume_one_day_back,
 lag (close,1) OVER (PARTITION BY ticker ORDER BY _date) AS close_one_day_back,
 lag (volume,2) OVER (PARTITION BY ticker ORDER BY _date) AS volume_two_day_back,
 lag (close,2) OVER (PARTITION BY ticker ORDER BY _date) AS close_two_day_back,
 lag (volume,3) OVER (PARTITION BY ticker ORDER BY _date) AS volume_three_day_back,
 lag (close,3) OVER (PARTITION BY ticker ORDER BY _date) AS close_three_day_back,
 lag (volume,4) OVER (PARTITION BY ticker ORDER BY _date) AS volume_four_day_back,
 lag (close,4) OVER (PARTITION BY ticker ORDER BY _date) AS close_four_day_back,
 lag (volume,5) OVER (PARTITION BY ticker ORDER BY _date) AS volume_five_day_back,
 lag (close,5) OVER (PARTITION BY ticker ORDER BY _date) AS close_five_day_back,
 lag (volume,6) OVER (PARTITION BY ticker ORDER BY _date) AS volume_six_day_back,
 lag (close,6) OVER (PARTITION BY ticker ORDER BY _date) AS close_six_day_back,
 lag (volume,7) OVER (PARTITION BY ticker ORDER BY _date) AS volume_seven_day_back,
 lag (close,7) OVER (PARTITION BY ticker ORDER BY _date) AS close_seven_day_back,
 lag (volume,8) OVER (PARTITION BY ticker ORDER BY _date) AS volume_eight_day_back,
 lag (close,8) OVER (PARTITION BY ticker ORDER BY _date) AS close_eight_day_back,
 lag (volume,9) OVER (PARTITION BY ticker ORDER BY _date) AS volume_nine_day_back,
 lag (close,9) OVER (PARTITION BY ticker ORDER BY _date) AS close_nine_day_back,
 lag (volume,10) OVER (PARTITION BY ticker ORDER BY _date) AS volume_ten_day_back,
 lag (close,10) OVER (PARTITION BY ticker ORDER BY _date) AS close_ten_day_back,
 lag (volume,11) OVER (PARTITION BY ticker ORDER BY _date) AS volume_eleven_day_back,
 lag (close,11) OVER (PARTITION BY ticker ORDER BY _date) AS close_eleven_day_back,
 lag (volume,12) OVER (PARTITION BY ticker ORDER BY _date) AS volume_twelve_day_back,
 lag (close,12) OVER (PARTITION BY ticker ORDER BY _date) AS close_twelve_day_back,
 lag (volume,13) OVER (PARTITION BY ticker ORDER BY _date) AS volume_thirteen_day_back,
 lag (close,13) OVER (PARTITION BY ticker ORDER BY _date) AS close_thirteen_day_back,
 lag (volume,14) OVER (PARTITION BY ticker ORDER BY _date) AS volume_fourteen_day_back,
 lag (close,14) OVER (PARTITION BY ticker ORDER BY _date) AS close_fourteen_day_back,
 lag (volume,15) OVER (PARTITION BY ticker ORDER BY _date) AS volume_fiveteen_day_back,
 lag (close,15) OVER (PARTITION BY ticker ORDER BY _date) AS close_fiveteen_day_back,
 lag (volume,16) OVER (PARTITION BY ticker ORDER BY _date) AS volume_sixteen_day_back,
 lag (close,16) OVER (PARTITION BY ticker ORDER BY _date) AS close_sixteen_day_back,
 lag (volume,17) OVER (PARTITION BY ticker ORDER BY _date) AS volume_seveteen_day_back,
 lag (close,17) OVER (PARTITION BY ticker ORDER BY _date) AS close_seveteen_day_back,
 lag (volume,18) OVER (PARTITION BY ticker ORDER BY _date) AS volume_eighteen_day_back,
 lag (close,18) OVER (PARTITION BY ticker ORDER BY _date) AS close_eighteen_day_back,
 lag (volume,19) OVER (PARTITION BY ticker ORDER BY _date) AS volume_nineteen_day_back,
 lag (close,19) OVER (PARTITION BY ticker ORDER BY _date) AS close_nineteen_day_back,
 lag (volume,20) OVER (PARTITION BY ticker ORDER BY _date) AS volume_twenty_day_back,
 lag (close,20) OVER (PARTITION BY ticker ORDER BY _date) AS close_twenty_day_back,
 lag (volume,21) OVER (PARTITION BY ticker ORDER BY _date) AS volume_twenty_one_day_back,
 lag (close,21) OVER (PARTITION BY ticker ORDER BY _date) AS close_twenty_one_day_back,
 lag (volume,22) OVER (PARTITION BY ticker ORDER BY _date) AS volume_twenty_two_day_back,
 lag (close,22) OVER (PARTITION BY ticker ORDER BY _date) AS close_twenty_two_day_back,
 lag (volume,23) OVER (PARTITION BY ticker ORDER BY _date) AS volume_twenty_three_day_back,
 lag (close,23) OVER (PARTITION BY ticker ORDER BY _date) AS close_twenty_three_day_back,
 lag (volume,24) OVER (PARTITION BY ticker ORDER BY _date) AS volume_twenty_four_day_back,
 lag (close,24) OVER (PARTITION BY ticker ORDER BY _date) AS close_twenty_four_day_back,
 lag (volume,25) OVER (PARTITION BY ticker ORDER BY _date) AS volume_twenty_five_day_back,
 lag (close,25) OVER (PARTITION BY ticker ORDER BY _date) AS close_twenty_five_day_back,
 lag (volume,26) OVER (PARTITION BY ticker ORDER BY _date) AS volume_twenty_six_day_back,
 lag (close,26) OVER (PARTITION BY ticker ORDER BY _date) AS close_twenty_six_day_back,
 lag (volume,27) OVER (PARTITION BY ticker ORDER BY _date) AS volume_twenty_seven_day_back,
 lag (close,27) OVER (PARTITION BY ticker ORDER BY _date) AS close_twenty_seven_day_back,
 lag (volume,28) OVER (PARTITION BY ticker ORDER BY _date) AS volume_twenty_eight_day_back,
 lag (close,28) OVER (PARTITION BY ticker ORDER BY _date) AS close_twenty_eight_day_back,
 lag (volume,29) OVER (PARTITION BY ticker ORDER BY _date) AS volume_twenty_nine_day_back,
 lag (close,29) OVER (PARTITION BY ticker ORDER BY _date) AS close_twenty_nine_day_back,
 lag (volume,30) OVER (PARTITION BY ticker ORDER BY _date) AS volume_thirty_day_back,
 lag (close,30) OVER (PARTITION BY ticker ORDER BY _date) AS close_thirty_day_back,
 lag (volume,31) OVER (PARTITION BY ticker ORDER BY _date) AS volume_thirty_one_day_back,
 lag (close,31) OVER (PARTITION BY ticker ORDER BY _date) AS close_thirty_one_day_back,
 lag (volume,32) OVER (PARTITION BY ticker ORDER BY _date) AS volume_thirty_two_day_back,
 lag (close,32) OVER (PARTITION BY ticker ORDER BY _date) AS close_thirty_two_day_back,
 lag (volume,33) OVER (PARTITION BY ticker ORDER BY _date) AS volume_thirty_three_day_back,
 lag (close,33) OVER (PARTITION BY ticker ORDER BY _date) AS close_thirty_three_day_back,
 lag (volume,34) OVER (PARTITION BY ticker ORDER BY _date) AS volume_thirty_four_day_back,
 lag (close,34) OVER (PARTITION BY ticker ORDER BY _date) AS close_thirty_four_day_back,
 lag (volume,35) OVER (PARTITION BY ticker ORDER BY _date) AS volume_thirty_five_day_back,
 lag (close,35) OVER (PARTITION BY ticker ORDER BY _date) AS close_thirty_five_day_back,
 lag (volume,36) OVER (PARTITION BY ticker ORDER BY _date) AS volume_thirty_six_day_back,
 lag (close,36) OVER (PARTITION BY ticker ORDER BY _date) AS close_thirty_six_day_back,
 lag (volume,37) OVER (PARTITION BY ticker ORDER BY _date) AS volume_thirty_seven_day_back,
 lag (close,37) OVER (PARTITION BY ticker ORDER BY _date) AS close_thirty_seven_day_back,
 lag (volume,38) OVER (PARTITION BY ticker ORDER BY _date) AS volume_thirty_eight_day_back,
 lag (close,38) OVER (PARTITION BY ticker ORDER BY _date) AS close_thirty_eight_day_back,
 lag (volume,39) OVER (PARTITION BY ticker ORDER BY _date) AS volume_thirty_nine_day_back,
 lag (close,39) OVER (PARTITION BY ticker ORDER BY _date) AS close_thirty_nine_day_back,
 lag (volume,40) OVER (PARTITION BY ticker ORDER BY _date) AS volume_forty_day_back,
 lag (close,40) OVER (PARTITION BY ticker ORDER BY _date) AS close_forty_day_back,
 lag (volume,41) OVER (PARTITION BY ticker ORDER BY _date) AS volume_forty_one_day_back,
 lag (close,41) OVER (PARTITION BY ticker ORDER BY _date) AS close_forty_one_day_back,
 lag (volume,42) OVER (PARTITION BY ticker ORDER BY _date) AS volume_forty_two_day_back,
 lag (close,42) OVER (PARTITION BY ticker ORDER BY _date) AS close_forty_two_day_back,
 lag (volume,43) OVER (PARTITION BY ticker ORDER BY _date) AS volume_forty_three_day_back,
 lag (close,43) OVER (PARTITION BY ticker ORDER BY _date) AS close_forty_three_day_back,
 lag (volume,44) OVER (PARTITION BY ticker ORDER BY _date) AS volume_forty_four_day_back,
 lag (close,44) OVER (PARTITION BY ticker ORDER BY _date) AS close_forty_four_day_back,
 lag (volume,45) OVER (PARTITION BY ticker ORDER BY _date) AS volume_forty_five_day_back,
 lag (close,45) OVER (PARTITION BY ticker ORDER BY _date) AS close_forty_five_day_back,
 lag (volume,46) OVER (PARTITION BY ticker ORDER BY _date) AS volume_forty_six_day_back,
 lag (close,46) OVER (PARTITION BY ticker ORDER BY _date) AS close_forty_six_day_back,
 lag (volume,47) OVER (PARTITION BY ticker ORDER BY _date) AS volume_forty_seven_day_back,
 lag (close,47) OVER (PARTITION BY ticker ORDER BY _date) AS close_forty_seven_day_back,
 lag (volume,48) OVER (PARTITION BY ticker ORDER BY _date) AS volume_forty_eight_day_back,
 lag (close,48) OVER (PARTITION BY ticker ORDER BY _date) AS close_forty_eight_day_back,
 lag (volume,49) OVER (PARTITION BY ticker ORDER BY _date) AS volume_forty_nine_day_back,
 lag (close,49) OVER (PARTITION BY ticker ORDER BY _date) AS close_forty_nine_day_back,
 lag (volume,50) OVER (PARTITION BY ticker ORDER BY _date) AS volume_fifty_day_back,
 lag (close,50) OVER (PARTITION BY ticker ORDER BY _date) AS close_fifty_day_back,
 lag (volume,51) OVER (PARTITION BY ticker ORDER BY _date) AS volume_fifty_one_day_back,
 lag (close,51) OVER (PARTITION BY ticker ORDER BY _date) AS close_fifty_one_day_back,
 lag (volume,52) OVER (PARTITION BY ticker ORDER BY _date) AS volume_fifty_two_day_back,
 lag (close,52) OVER (PARTITION BY ticker ORDER BY _date) AS close_fifty_two_day_back,
 lag (volume,53) OVER (PARTITION BY ticker ORDER BY _date) AS volume_fifty_three_day_back,
 lag (close,53) OVER (PARTITION BY ticker ORDER BY _date) AS close_fifty_three_day_back,
 lag (volume,54) OVER (PARTITION BY ticker ORDER BY _date) AS volume_fifty_four_day_back,
 lag (close,54) OVER (PARTITION BY ticker ORDER BY _date) AS close_fifty_four_day_back,
 lag (volume,55) OVER (PARTITION BY ticker ORDER BY _date) AS volume_fifty_five_day_back,
 lag (close,55) OVER (PARTITION BY ticker ORDER BY _date) AS close_fifty_five_day_back
 from a )
 select * from b where _date = (select max(_date) from a));