-- Generated by the database client.
CREATE TABLE if not exists yahoo_check_result(
    ticker varchar(100),
    _date DATE,
    close numeric(38,8),
    open numeric(38,8),
    high numeric(38,8),
    low numeric(38,8),
    volume numeric(38,8)
);

TRUNCATE TABLE yahoo_check_result;